import type { AgentStep, AgentStepStatus as UiAgentStepStatus, MockSong } from "@/lib/mock-data";

import type {
  AgentConsoleRunViewModel,
  AgentRunApiItem,
  AgentRunDetailApiResponse,
  AgentStepApiItem,
  DashboardAgentRunsApiResponse,
  DashboardAgentSummaryViewModel,
  DashboardFeedbackDistributionViewModel,
  DashboardMetricViewModel,
  DashboardOverviewApiResponse,
  GeneratedPlaylistPreviewViewModel,
  JsonObject,
  KaraokeSessionApiItem,
  KaraokeSessionDetailApiResponse,
  KaraokeSessionMemberApiItem,
  PlaylistGenerateResponse,
  RecommendationReasonApiItem,
  SongApiItem,
  TasteProfileSummaryApiItem,
  TimelineSessionMemberViewModel,
  TimelineSessionSummaryViewModel
} from "./types";

const coverTones: MockSong["coverTone"][] = ["cyan", "mint", "amber", "coral", "violet"];

export function scoreToDisplayScore(score: number | null | undefined) {
  if (typeof score !== "number" || Number.isNaN(score)) {
    return 0;
  }

  return Math.round(Math.max(0, Math.min(1, score)) * 100);
}

export function toCamelCaseKey(value: string) {
  return value.replace(/_([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

export function shallowCamelCase<T extends Record<string, unknown>>(value: T) {
  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [toCamelCaseKey(key), item])
  );
}

export function mapAgentStepStatus(status: AgentStepApiItem["status"]): UiAgentStepStatus {
  if (status === "succeeded") return "completed";
  if (status === "running") return "running";
  if (status === "queued") return "queued";
  return "warning";
}

export function adaptSongToMockSong(song: SongApiItem, index = 0): MockSong {
  return {
    id: song.id,
    title: song.title,
    artist: song.artist_name,
    language: song.language,
    mood: song.moods[0] ?? "demo",
    energy: scoreToDisplayScore(song.energy),
    vocalDifficulty: scoreToDisplayScore(song.vocal_difficulty),
    fitScore: 88,
    sceneTags: song.scene_tags,
    reason: "Loaded from the verified backend demo catalog.",
    coverTone: coverTones[index % coverTones.length]
  };
}

export function isPlaylistGenerateResponseUsable(
  response: PlaylistGenerateResponse | null | undefined
) {
  if (!response?.playlist || !response.agent_run) {
    return false;
  }

  const { playlist, agent_run: agentRun } = response;

  return Boolean(
    playlist.id &&
      playlist.title &&
      playlist.status &&
      playlist.scene_type &&
      isPositiveNumber(playlist.target_length) &&
      agentRun.id &&
      agentRun.status &&
      Array.isArray(playlist.items) &&
      playlist.items.length > 0 &&
      playlist.items.every(
        (item) =>
          item.id &&
          item.position >= 1 &&
          isUsableNumber(item.fit_score) &&
          item.song?.title &&
          item.song?.artist_name &&
          Array.isArray(item.reasons) &&
          item.reasons.some((reason) => Boolean(reason.short_reason))
      )
  );
}

export function adaptGeneratedPlaylistToPlannerPreview(
  response: PlaylistGenerateResponse
): GeneratedPlaylistPreviewViewModel {
  const sortedItems = [...response.playlist.items].sort(
    (left, right) => left.position - right.position
  );
  const tracks = sortedItems.slice(0, 5).map((item) => ({
    id: item.id,
    title: item.song.title,
    artist: item.song.artist_name,
    fitScoreLabel: `${scoreToDisplayScore(item.fit_score)}% fit`,
    reason: safeRecommendationReasonPreview(item.reasons[0])
  }));

  return {
    playlistId: formatShortId(response.playlist.id),
    title: response.playlist.title,
    statusLabel: formatLabel(response.playlist.status),
    sceneLabel: formatSceneType(response.playlist.scene_type),
    trackCountLabel: `${sortedItems.length} tracks`,
    targetLengthLabel: `${response.playlist.target_length} target tracks`,
    agentRunId: formatShortId(response.agent_run.id),
    agentRunStatusLabel: formatRunStatus(response.agent_run.status),
    workflowLabel: "Generated by deterministic mock workflow",
    tracks
  };
}

export function safeRecommendationReasonPreview(
  reason: RecommendationReasonApiItem | null | undefined
) {
  const value = reason?.short_reason?.trim();

  if (!value) {
    return "Recommendation reason summary unavailable.";
  }

  return value.length > 140 ? `${value.slice(0, 137)}...` : value;
}

export function getFirstUsableKaraokeSession(
  sessions: KaraokeSessionApiItem[] | null | undefined
) {
  return sessions?.find(isKaraokeSessionItemUsable) ?? null;
}

export function isKaraokeSessionsUsable(sessions: KaraokeSessionApiItem[] | null | undefined) {
  return Boolean(Array.isArray(sessions) && getFirstUsableKaraokeSession(sessions));
}

export function isKaraokeSessionDetailUsable(
  session: KaraokeSessionApiItem | null | undefined,
  detail: KaraokeSessionDetailApiResponse | null | undefined
) {
  if (!session || !detail) {
    return false;
  }

  return Boolean(
    isKaraokeSessionItemUsable(session) &&
      detail.id &&
      session.id === detail.id &&
      detail.title &&
      detail.scene_type &&
      detail.status &&
      isNonNegativeNumber(detail.members_count) &&
      isNonNegativeNumber(detail.playlists_count) &&
      isNonNegativeNumber(detail.feedback_count)
  );
}

export function isSessionMembersUsable(
  members: KaraokeSessionMemberApiItem[] | null | undefined
) {
  return Boolean(
    Array.isArray(members) &&
      members.length > 0 &&
      members.every(
        (member) =>
          member.id &&
          member.display_name &&
          member.role &&
          isUsableNumber(member.preference_weight)
      )
  );
}

export function adaptKaraokeSessionToTimelineSummary(
  session: KaraokeSessionApiItem,
  detail: KaraokeSessionDetailApiResponse
): TimelineSessionSummaryViewModel {
  return {
    id: detail.id,
    title: detail.title || session.title,
    sceneLabel: formatSceneType(detail.scene_type || session.scene_type),
    statusLabel: formatSessionStatus(detail.status || session.status),
    durationLabel: "90 min mock timeline",
    membersLabel: `${safeCount(detail.members_count)} members`,
    playlistsLabel: `${safeCount(detail.playlists_count)} playlists`,
    feedbackLabel: `${safeCount(detail.feedback_count)} feedback logs`,
    latestPlaylistLabel: formatShortId(detail.latest_playlist_id ?? session.latest_playlist_id),
    latestAgentRunLabel: formatShortId(detail.latest_agent_run_id),
    updatedLabel: formatDateTime(detail.updated_at ?? session.updated_at ?? detail.created_at)
  };
}

export function adaptSessionMembersToCompactView(
  members: KaraokeSessionMemberApiItem[]
): TimelineSessionMemberViewModel[] {
  return members.map((member) => ({
    id: member.id,
    name: member.display_name,
    role: formatMemberRole(member.role),
    weightLabel: `${scoreToDisplayScore(member.preference_weight)}% weight`,
    profileLabel: formatTasteProfileSummary(member.profile_summary)
  }));
}

export function adaptAgentStepToMockStep(step: AgentStepApiItem): AgentStep {
  return {
    id: step.id,
    tool: step.tool_name ?? step.step_type,
    status: mapAgentStepStatus(step.status),
    latencyMs: step.latency_ms ?? 0,
    inputSummary: summarizeJson(step.input_summary),
    outputSummary: summarizeJson(step.output_summary ?? errorSummary(step.error_message))
  };
}

export function isAgentRunUsable(
  run: AgentRunApiItem | null | undefined,
  detail: AgentRunDetailApiResponse | null | undefined
) {
  if (!run || !detail) {
    return false;
  }

  return Boolean(
    run.id &&
      detail.id &&
      run.id === detail.id &&
      detail.objective &&
      detail.run_type &&
      detail.status
  );
}

export function isAgentStepsUsable(steps: AgentStepApiItem[] | null | undefined) {
  return Boolean(
    Array.isArray(steps) &&
      steps.length > 0 &&
      steps.every((step) => step.id && step.step_index >= 1 && step.step_type && step.status)
  );
}

export function adaptAgentRunToConsoleRun(
  run: AgentRunApiItem,
  detail: AgentRunDetailApiResponse
): AgentConsoleRunViewModel {
  return {
    id: run.id,
    mode: `${formatRunType(detail.run_type)} / ${run.model_provider}`,
    objective: detail.objective,
    status: formatRunStatus(detail.status),
    startedAt: formatDateTime(run.created_at),
    totalLatencyMs: safeCount(detail.latency_ms ?? run.latency_ms),
    stepsCount: detail.steps_count
  };
}

export function isDashboardOverviewUsable(overview: DashboardOverviewApiResponse | null | undefined) {
  if (!overview) {
    return false;
  }

  const hasCounts =
    isPositiveNumber(overview.sessions_count) ||
    isPositiveNumber(overview.playlists_count) ||
    isPositiveNumber(overview.feedback_count);
  const hasFeedbackTypes = Array.isArray(overview.top_feedback_types) && overview.top_feedback_types.length > 0;
  const hasLatency = isUsableNumber(overview.avg_agent_latency_ms);

  return hasCounts || hasFeedbackTypes || hasLatency;
}

export function isDashboardAgentRunsUsable(agentRuns: DashboardAgentRunsApiResponse | null | undefined) {
  if (!agentRuns) {
    return false;
  }

  const statusTotal = (agentRuns.by_status ?? []).reduce((sum, item) => sum + safeCount(item.count), 0);
  const toolTotal = (agentRuns.by_tool ?? []).reduce((sum, item) => sum + safeCount(item.count), 0);

  return statusTotal > 0 || toolTotal > 0 || (agentRuns.recent_failures ?? []).length > 0;
}

export function adaptDashboardAgentRunsToSummary(
  agentRuns: DashboardAgentRunsApiResponse
): DashboardAgentSummaryViewModel {
  const succeededRuns = countAgentRunsByStatus(agentRuns, "succeeded");
  const failedRuns = countAgentRunsByStatus(agentRuns, "failed");
  const totalRuns = (agentRuns.by_status ?? []).reduce((sum, item) => sum + safeCount(item.count), 0);
  const successRate = totalRuns > 0 ? Math.round((succeededRuns / totalRuns) * 100) : null;

  return {
    totalRuns,
    succeededRuns,
    failedRuns,
    successRate,
    statusLabel: totalRuns > 0 ? `${succeededRuns}/${totalRuns} succeeded` : "No persisted runs"
  };
}

export function adaptDashboardOverviewToMetrics(
  overview: DashboardOverviewApiResponse,
  agentSummary: DashboardAgentSummaryViewModel | null = null
): DashboardMetricViewModel[] {
  const avgLatency = formatLatency(overview.avg_agent_latency_ms);

  return [
    {
      label: "Sessions",
      value: formatCount(overview.sessions_count),
      delta: "API"
    },
    {
      label: "Playlists",
      value: formatCount(overview.playlists_count),
      delta: "API"
    },
    {
      label: "Feedback logs",
      value: formatCount(overview.feedback_count),
      delta: "API"
    },
    {
      label: agentSummary ? "Agent success" : "Avg latency",
      value: agentSummary?.successRate != null ? `${agentSummary.successRate}%` : avgLatency,
      delta: agentSummary?.statusLabel ?? "API"
    }
  ];
}

export function adaptDashboardFeedbackDistribution(
  overview: DashboardOverviewApiResponse
): DashboardFeedbackDistributionViewModel[] {
  return (overview.top_feedback_types ?? [])
    .filter((item) => safeCount(item.count) > 0)
    .map((item) => ({
      name: formatFeedbackType(item.feedback_type),
      value: safeCount(item.count)
    }));
}

export function summarizeJson(value: JsonObject | null | undefined) {
  if (!value) {
    return "No summary provided.";
  }

  const summary = value.summary;
  if (typeof summary === "string") {
    return summary;
  }

  const summaryEntries = Object.entries(value)
    .filter(([key]) => !isSensitiveSummaryKey(key))
    .slice(0, 3)
    .map(([key, item]) => `${toCamelCaseKey(key)}: ${formatSummaryValue(item)}`)
    .join("; ");

  return summaryEntries || "Summary withheld.";
}

function isKaraokeSessionItemUsable(session: KaraokeSessionApiItem | null | undefined) {
  return Boolean(
    session &&
      session.id &&
      session.title &&
      session.scene_type &&
      session.status &&
      isNonNegativeNumber(session.members_count) &&
      isNonNegativeNumber(session.playlists_count)
  );
}

function formatSceneType(value: string) {
  if (value === "ktv") return "KTV";
  if (value === "car") return "Car";
  if (value === "home_party") return "Home party";
  if (value === "custom") return "Custom";
  return formatLabel(value);
}

function formatSessionStatus(value: string) {
  return formatLabel(value);
}

function formatMemberRole(value: string) {
  return formatLabel(value);
}

function formatTasteProfileSummary(profile: TasteProfileSummaryApiItem | null | undefined) {
  if (!profile) {
    return "No profile summary";
  }

  const genres = (profile.favorite_genres ?? []).filter(Boolean).slice(0, 2).join(", ");
  const language = getTopAffinityKey(profile.language_affinity);
  const confidence =
    typeof profile.confidence === "number" ? `${scoreToDisplayScore(profile.confidence)}% confidence` : "";

  return [genres ? `Genres: ${genres}` : "", language ? `Top language: ${language}` : "", confidence]
    .filter(Boolean)
    .slice(0, 2)
    .join(" | ") || "Profile summary available";
}

function getTopAffinityKey(value: JsonObject | null | undefined) {
  const entries = Object.entries(value ?? {})
    .filter((entry): entry is [string, number] => typeof entry[1] === "number")
    .sort((left, right) => right[1] - left[1]);

  return entries[0]?.[0] ? formatLabel(entries[0][0]) : "";
}

function formatShortId(value: string | null | undefined) {
  if (!value) {
    return "none";
  }

  return value.length > 8 ? `${value.slice(0, 8)}...` : value;
}

function formatLabel(value: string) {
  return value
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function errorSummary(errorMessage: string | null | undefined): JsonObject | null {
  if (!errorMessage) {
    return null;
  }

  return {
    summary: errorMessage
  };
}

function formatSummaryValue(value: unknown) {
  if (Array.isArray(value)) {
    return `${value.length} items`;
  }

  if (value && typeof value === "object") {
    return "object";
  }

  return String(value ?? "none");
}

function countAgentRunsByStatus(agentRuns: DashboardAgentRunsApiResponse, status: string) {
  return safeCount((agentRuns.by_status ?? []).find((item) => item.status === status)?.count);
}

function formatCount(value: number | null | undefined) {
  return safeCount(value).toLocaleString("en-US");
}

function formatLatency(value: number | null | undefined) {
  if (!isUsableNumber(value)) {
    return "n/a";
  }

  return `${Math.round(Math.max(0, value))}ms`;
}

function formatFeedbackType(value: string) {
  return value
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function formatRunType(value: string) {
  return value
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function formatRunStatus(value: string) {
  if (value === "succeeded") return "succeeded";
  if (value === "failed") return "failed";
  if (value === "running") return "running";
  if (value === "queued") return "queued";
  if (value === "cancelled") return "cancelled";
  return value;
}

function isSensitiveSummaryKey(key: string) {
  const normalized = key.toLowerCase();
  return (
    normalized.includes("prompt") ||
    normalized.includes("provider_payload") ||
    normalized.includes("payload_raw") ||
    normalized.includes("chain") ||
    normalized.includes("thought") ||
    normalized.includes("message")
  );
}

function formatDateTime(value: string | null | undefined) {
  if (!value) {
    return "n/a";
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "n/a";
  }

  return parsed.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit"
  });
}

function safeCount(value: number | null | undefined) {
  return isUsableNumber(value) ? Math.max(0, Math.round(value)) : 0;
}

function isNonNegativeNumber(value: number | null | undefined) {
  return isUsableNumber(value) && value >= 0;
}

function isPositiveNumber(value: number | null | undefined) {
  return isUsableNumber(value) && value > 0;
}

function isUsableNumber(value: number | null | undefined): value is number {
  return typeof value === "number" && Number.isFinite(value);
}
